const SOURCE = {
  id: "manual-catalog",
  name: "Кутно · без плиты",
  type: "kutno-manual-catalog",
  note: "Холодный рецепт, который можно приготовить руками и базовыми ручными инструментами.",
  url: "",
  license: "",
};

const ingredient = (name, amount, unit, options = {}) => ({ name, amount, unit, ...options });

const RECIPES = [
  {
    id: "manual-vegetable-salad",
    title: "Салат из помидоров и огурцов",
    subtitle: "Свежие овощи с простой заправкой",
    cuisine: "Домашняя кухня",
    flag: "🥗",
    course: "салат",
    protein: "без мяса",
    minutes: 10,
    difficulty: "легко",
    servings: 2,
    equipment: ["Нож", "Разделочная доска", "Миска"],
    ingredients: [
      ingredient("помидоры", 300, "г", { aliases: ["томаты"] }),
      ingredient("огурец", 250, "г"),
      ingredient("репчатый лук", 50, "г", { aliases: ["лук"], role: "optional" }),
      ingredient("растительное масло", 20, "мл", { pantry: true }),
      ingredient("соль", 0, "", { pantry: true }),
      ingredient("чёрный перец", 0, "", { pantry: true, role: "optional" }),
    ],
    steps: [
      "Нарежьте помидоры и огурец удобными кусочками, лук — тонкими полукольцами.",
      "Сложите овощи в миску, посолите и аккуратно перемешайте.",
      "Заправьте маслом и подавайте сразу, пока овощи не дали слишком много сока.",
    ],
    nutrition: { calories: 150, protein: 3, fat: 10, carbs: 12 },
    tip: "Солите непосредственно перед подачей, чтобы салат оставался свежим.",
  },
  {
    id: "manual-greek-salad",
    title: "Греческий салат",
    subtitle: "Овощи, фета и оливковое масло",
    cuisine: "Греция",
    flag: "🇬🇷",
    course: "салат",
    protein: "без мяса",
    minutes: 12,
    difficulty: "легко",
    servings: 2,
    equipment: ["Нож", "Разделочная доска", "Миска"],
    ingredients: [
      ingredient("помидоры", 300, "г", { aliases: ["томаты"] }),
      ingredient("огурец", 220, "г"),
      ingredient("сыр фета", 140, "г", { aliases: ["фета", "брынза"] }),
      ingredient("сладкий перец", 150, "г", { aliases: ["болгарский перец"] }),
      ingredient("красный лук", 50, "г", { aliases: ["репчатый лук", "лук"], role: "optional" }),
      ingredient("оливки", 70, "г", { role: "optional" }),
      ingredient("оливковое масло", 25, "мл", { pantry: true }),
      ingredient("соль", 0, "", { pantry: true }),
    ],
    steps: [
      "Крупно нарежьте помидоры, огурец и сладкий перец, лук нарежьте тонко.",
      "Сложите овощи в миску, добавьте оливки и осторожно перемешайте с маслом.",
      "Положите сверху крупные кусочки феты и слегка посолите овощи вокруг сыра.",
    ],
    nutrition: { calories: 365, protein: 14, fat: 28, carbs: 15 },
    tip: "Фету лучше не крошить слишком мелко — крупные кусочки сохраняют текстуру.",
  },
  {
    id: "manual-caprese",
    title: "Капрезе",
    subtitle: "Помидоры, моцарелла и базилик",
    cuisine: "Италия",
    flag: "🇮🇹",
    course: "закуска",
    protein: "без мяса",
    minutes: 8,
    difficulty: "легко",
    servings: 2,
    equipment: ["Нож", "Разделочная доска"],
    ingredients: [
      ingredient("помидоры", 320, "г", { aliases: ["томаты"] }),
      ingredient("моцарелла", 250, "г"),
      ingredient("свежий базилик", 15, "г", { aliases: ["базилик"], role: "optional" }),
      ingredient("оливковое масло", 20, "мл", { pantry: true }),
      ingredient("соль", 0, "", { pantry: true }),
      ingredient("чёрный перец", 0, "", { pantry: true, role: "optional" }),
    ],
    steps: [
      "Нарежьте помидоры и моцареллу ломтиками примерно одинаковой толщины.",
      "Разложите их внахлёст на тарелке и добавьте листья базилика.",
      "Посолите, полейте оливковым маслом и при желании добавьте перец.",
    ],
    nutrition: { calories: 430, protein: 25, fat: 31, carbs: 13 },
    tip: "Хорошие спелые помидоры здесь важнее любых дополнительных приправ.",
  },
  {
    id: "manual-cheese-sandwich",
    title: "Сэндвич с сыром и овощами",
    subtitle: "Хлеб, сыр, помидор и огурец",
    cuisine: "Домашняя кухня",
    flag: "🥪",
    course: "перекус",
    protein: "без мяса",
    minutes: 7,
    difficulty: "легко",
    servings: 2,
    equipment: ["Нож", "Разделочная доска", "Руки"],
    ingredients: [
      ingredient("хлеб", 4, "ломт."),
      ingredient("твёрдый сыр", 120, "г", { aliases: ["сыр"] }),
      ingredient("помидоры", 160, "г", { aliases: ["томаты"] }),
      ingredient("огурец", 120, "г"),
      ingredient("сливочное масло", 20, "г", { role: "optional" }),
      ingredient("соль", 0, "", { pantry: true }),
    ],
    steps: [
      "Тонко нарежьте сыр, помидор и огурец.",
      "При желании смажьте хлеб сливочным маслом и разложите начинку на двух ломтиках.",
      "Накройте оставшимся хлебом, слегка прижмите и разрежьте пополам.",
    ],
    nutrition: { calories: 455, protein: 22, fat: 22, carbs: 42 },
    tip: "Промокните помидор салфеткой, чтобы хлеб дольше не размокал.",
  },
  {
    id: "manual-tuna-sandwich",
    title: "Сэндвич с тунцом",
    subtitle: "Тунец, огурец и лёгкая йогуртовая заправка",
    cuisine: "Мировая кухня",
    flag: "🥪",
    course: "перекус",
    protein: "рыба и морепродукты",
    minutes: 10,
    difficulty: "легко",
    servings: 2,
    equipment: ["Нож", "Миска", "Вилка", "Руки"],
    ingredients: [
      ingredient("хлеб", 4, "ломт."),
      ingredient("консервированный тунец", 180, "г", { aliases: ["тунец"] }),
      ingredient("огурец", 120, "г"),
      ingredient("йогурт", 50, "г", { aliases: ["греческий йогурт", "майонез"] }),
      ingredient("лимонный сок", 10, "мл", { aliases: ["лимон"], role: "optional" }),
      ingredient("соль", 0, "", { pantry: true }),
    ],
    steps: [
      "Слейте жидкость с тунца и разомните его вилкой с йогуртом.",
      "Мелко нарежьте огурец, вмешайте его в тунцовую начинку и посолите.",
      "Распределите начинку между ломтиками хлеба и соберите два сэндвича.",
    ],
    nutrition: { calories: 390, protein: 35, fat: 8, carbs: 43 },
    tip: "Хорошо слитый тунец делает начинку плотной и не размягчает хлеб.",
  },
  {
    id: "manual-ham-cheese-sandwich",
    title: "Сэндвич с ветчиной и сыром",
    subtitle: "Сытный холодный сэндвич за пять минут",
    cuisine: "Мировая кухня",
    flag: "🥪",
    course: "перекус",
    protein: "мясо",
    minutes: 5,
    difficulty: "легко",
    servings: 2,
    equipment: ["Нож", "Разделочная доска", "Руки"],
    ingredients: [
      ingredient("хлеб", 4, "ломт."),
      ingredient("ветчина", 140, "г"),
      ingredient("твёрдый сыр", 100, "г", { aliases: ["сыр"] }),
      ingredient("помидоры", 120, "г", { aliases: ["томаты"], role: "optional" }),
      ingredient("горчица", 20, "г", { role: "optional" }),
    ],
    steps: [
      "Нарежьте сыр и помидор тонкими ломтиками.",
      "При желании смажьте хлеб горчицей, затем выложите ветчину, сыр и помидор.",
      "Накройте вторыми ломтиками хлеба и разрежьте сэндвичи пополам.",
    ],
    nutrition: { calories: 475, protein: 31, fat: 21, carbs: 40 },
    tip: "Слой сыра между хлебом и помидором защищает мякиш от влаги.",
  },
  {
    id: "manual-chickpea-salad",
    title: "Салат из нута и овощей",
    subtitle: "Сытный холодный салат с лимонной заправкой",
    cuisine: "Средиземноморская кухня",
    flag: "🥗",
    course: "салат",
    protein: "без мяса",
    minutes: 12,
    difficulty: "легко",
    servings: 2,
    equipment: ["Нож", "Разделочная доска", "Миска"],
    ingredients: [
      ingredient("варёный нут", 300, "г", { aliases: ["нут"] }),
      ingredient("помидоры", 220, "г", { aliases: ["томаты"] }),
      ingredient("огурец", 180, "г"),
      ingredient("репчатый лук", 50, "г", { aliases: ["лук"], role: "optional" }),
      ingredient("лимонный сок", 20, "мл", { aliases: ["лимон"] }),
      ingredient("оливковое масло", 20, "мл", { pantry: true }),
      ingredient("соль", 0, "", { pantry: true }),
    ],
    steps: [
      "Промойте готовый нут и хорошо обсушите.",
      "Нарежьте помидоры, огурец и лук, соедините с нутом в миске.",
      "Заправьте лимонным соком, маслом и солью, затем перемешайте.",
    ],
    nutrition: { calories: 440, protein: 18, fat: 15, carbs: 59 },
    tip: "Консервированный нут подходит без дополнительной варки — его достаточно промыть.",
  },
  {
    id: "manual-bean-tuna-salad",
    title: "Салат с тунцом и фасолью",
    subtitle: "Белковый салат из консервов и свежих овощей",
    cuisine: "Средиземноморская кухня",
    flag: "🥗",
    course: "салат",
    protein: "рыба и морепродукты",
    minutes: 10,
    difficulty: "легко",
    servings: 2,
    equipment: ["Нож", "Миска", "Вилка"],
    ingredients: [
      ingredient("консервированный тунец", 180, "г", { aliases: ["тунец"] }),
      ingredient("консервированная фасоль", 240, "г", { aliases: ["фасоль"] }),
      ingredient("помидоры", 200, "г", { aliases: ["томаты"] }),
      ingredient("репчатый лук", 50, "г", { aliases: ["лук"], role: "optional" }),
      ingredient("лимонный сок", 15, "мл", { aliases: ["лимон"], role: "optional" }),
      ingredient("оливковое масло", 15, "мл", { pantry: true }),
      ingredient("соль", 0, "", { pantry: true }),
    ],
    steps: [
      "Промойте фасоль, с тунца слейте жидкость и разберите его вилкой.",
      "Нарежьте помидоры и лук, сложите всё в миску.",
      "Добавьте масло, лимонный сок и соль, затем аккуратно перемешайте.",
    ],
    nutrition: { calories: 460, protein: 44, fat: 14, carbs: 38 },
    tip: "Не перемешивайте слишком активно, чтобы фасоль осталась целой.",
  },
  {
    id: "manual-avocado-sandwich",
    title: "Сэндвич с авокадо",
    subtitle: "Авокадо, помидор и лимон на хлебе",
    cuisine: "Мировая кухня",
    flag: "🥑",
    course: "перекус",
    protein: "без мяса",
    minutes: 8,
    difficulty: "легко",
    servings: 2,
    equipment: ["Нож", "Вилка", "Руки"],
    ingredients: [
      ingredient("хлеб", 4, "ломт."),
      ingredient("авокадо", 2, "шт."),
      ingredient("помидоры", 160, "г", { aliases: ["томаты"] }),
      ingredient("лимонный сок", 15, "мл", { aliases: ["лимон"], role: "optional" }),
      ingredient("соль", 0, "", { pantry: true }),
      ingredient("чёрный перец", 0, "", { pantry: true, role: "optional" }),
    ],
    steps: [
      "Разомните мякоть авокадо вилкой с солью и лимонным соком.",
      "Нарежьте помидор тонкими ломтиками.",
      "Намажьте авокадо на хлеб, добавьте помидор и соберите сэндвичи.",
    ],
    nutrition: { calories: 510, protein: 11, fat: 29, carbs: 52 },
    tip: "Лимонный сок не только добавляет кислоту, но и замедляет потемнение авокадо.",
  },
  {
    id: "manual-yogurt-cucumber",
    title: "Огурцы с йогуртом",
    subtitle: "Холодная закуска с чесноком и зеленью",
    cuisine: "Балканская кухня",
    flag: "🥒",
    course: "закуска",
    protein: "без мяса",
    minutes: 8,
    difficulty: "легко",
    servings: 2,
    equipment: ["Нож", "Миска", "Ложка"],
    ingredients: [
      ingredient("огурец", 350, "г"),
      ingredient("йогурт", 250, "г", { aliases: ["греческий йогурт"] }),
      ingredient("чеснок", 1, "зубч.", { role: "optional" }),
      ingredient("укроп", 10, "г", { role: "optional" }),
      ingredient("соль", 0, "", { pantry: true }),
      ingredient("оливковое масло", 10, "мл", { pantry: true, role: "optional" }),
    ],
    steps: [
      "Нарежьте огурец небольшими кубиками или тонкими ломтиками.",
      "Смешайте йогурт с солью, измельчённым чесноком и укропом.",
      "Добавьте огурец, перемешайте и при желании полейте маслом.",
    ],
    nutrition: { calories: 205, protein: 13, fat: 10, carbs: 16 },
    tip: "Густой йогурт даст закуске более плотную текстуру.",
  },
  {
    id: "manual-cottage-cheese-spread",
    title: "Творожная намазка",
    subtitle: "Творог, йогурт и зелень на хлебе",
    cuisine: "Домашняя кухня",
    flag: "🥪",
    course: "перекус",
    protein: "без мяса",
    minutes: 7,
    difficulty: "легко",
    servings: 2,
    equipment: ["Миска", "Вилка", "Нож"],
    ingredients: [
      ingredient("творог", 250, "г"),
      ingredient("хлеб", 4, "ломт."),
      ingredient("йогурт", 40, "г", { aliases: ["сметана"] }),
      ingredient("укроп", 10, "г", { role: "optional" }),
      ingredient("чеснок", 1, "зубч.", { role: "optional" }),
      ingredient("соль", 0, "", { pantry: true }),
    ],
    steps: [
      "Разомните творог вилкой с йогуртом до кремовой консистенции.",
      "Добавьте соль, мелко нарезанный укроп и чеснок по желанию.",
      "Распределите намазку по ломтикам хлеба и подавайте сразу.",
    ],
    nutrition: { calories: 420, protein: 36, fat: 10, carbs: 46 },
    tip: "Количество йогурта зависит от влажности творога — добавляйте постепенно.",
  },
  {
    id: "manual-flatbread-wrap",
    title: "Рулет из лаваша с сыром и овощами",
    subtitle: "Холодный рулет без плиты и духовки",
    cuisine: "Домашняя кухня",
    flag: "🌯",
    course: "перекус",
    protein: "без мяса",
    minutes: 10,
    difficulty: "легко",
    servings: 2,
    equipment: ["Нож", "Разделочная доска", "Руки"],
    ingredients: [
      ingredient("лаваш", 2, "лист.", { aliases: ["лепёшка", "тортилья"] }),
      ingredient("твёрдый сыр", 140, "г", { aliases: ["сыр"] }),
      ingredient("помидоры", 180, "г", { aliases: ["томаты"] }),
      ingredient("огурец", 160, "г"),
      ingredient("йогурт", 50, "г", { aliases: ["сметана", "майонез"], role: "optional" }),
      ingredient("зелень", 15, "г", { role: "optional" }),
      ingredient("соль", 0, "", { pantry: true }),
    ],
    steps: [
      "Тонко нарежьте сыр, помидор и огурец.",
      "При желании смажьте лаваш йогуртом, затем разложите сыр и овощи.",
      "Плотно сверните рулеты, дайте им полежать две минуты и разрежьте пополам.",
    ],
    nutrition: { calories: 520, protein: 25, fat: 22, carbs: 55 },
    tip: "Не кладите начинку вплотную к краям, иначе она выпадет при сворачивании.",
  },
];

function formatNumber(value) {
  const rounded = Math.round(value * 100) / 100;
  return Number.isInteger(rounded) ? String(rounded) : String(rounded).replace(".", ",");
}

function scaledAmount(item, factor) {
  if (!Number.isFinite(Number(item.amount)) || Number(item.amount) === 0) return "по вкусу";
  let value = Number(item.amount) * factor;
  if (/г|мл/.test(item.unit)) value = Math.max(5, Math.round(value / 5) * 5);
  else if (/шт|ломт|лист/.test(item.unit)) value = Math.max(1, Math.round(value));
  else value = Math.round(value * 4) / 4;
  return `${formatNumber(value)} ${item.unit}`.trim();
}

export function manualRecipesForPortions(portions = 2) {
  const target = Math.min(8, Math.max(1, Number(portions) || 2));
  return RECIPES.map((recipe) => {
    const factor = target / recipe.servings;
    return {
      ...recipe,
      id: `manual:${recipe.id}`,
      ingredients: recipe.ingredients.map(({ amount, unit, ...item }) => ({
        ...item,
        amount: scaledAmount({ amount, unit }, factor),
      })),
      portions: target,
      source: { ...SOURCE, id: `manual:${recipe.id}` },
      uses: [],
      missing: [],
      why: "Готовится без плиты, духовки и электроприборов.",
      nutrition: { ...recipe.nutrition, estimated: true },
    };
  });
}
